{% set name = "parameterized" %}
{% set version = "0.7.5" %}
{% set sha256 = "b5e6af67b9e49485e30125b1c8f031ffa81a265ca08bfa73f31551bf03cf68c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - parameterized

about:
  home: https://github.com/wolever/parameterized
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parameterized testing with any Python test framework
  description: |
    Parameterized testing in Python sucks.
    parameterized fixes that. For everything. Parameterized testing for nose,
    parameterized testing for py.test, parameterized testing for unittest.
  dev_url: https://github.com/wolever/parameterized

extra:
  recipe-maintainers:
    - chohner
